groups:
- name: promtail_alerts
  rules:
  - alert: Promtail down
    expr: absent(up{job="promtail"})
    for: 10s
    labels:
      severity: critical
    annotations:
      description: "Promtail is down."