{
 "title": "Minion Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Minion's CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])) * 100), \"Host\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{Host}}"
    }
   ]
  },
  {
   "title": "CAdvisor Dashboards",
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 0 },
   "content": "- [cadvisor-minion-1.pennsignals.uphs.upenn.edu](http://cadvisor-minion-1.pennsignals.uphs.upenn.edu/)\n- [cadvisor-minion-2.pennsignals.uphs.upenn.edu](http://cadvisor-minion-2.pennsignals.uphs.upenn.edu/)\n- [cadvisor-minion-3.pennsignals.uphs.upenn.edu](http://cadvisor-minion-3.pennsignals.uphs.upenn.edu/)\n- [cadvisor-minion-4.pennsignals.uphs.upenn.edu](http://cadvisor-minion-4.pennsignals.uphs.upenn.edu/)\n- [cadvisor-minion-5.pennsignals.uphs.upenn.edu](http://cadvisor-minion-5.pennsignals.uphs.upenn.edu/)\n- [cadvisor-minion-6.pennsignals.uphs.upenn.edu](http://cadvisor-minion-6.pennsignals.uphs.upenn.edu/)\n- [cadvisor-minion-8.pennsignals.uphs.upenn.edu](http://cadvisor-minion-8.pennsignals.uphs.upenn.edu/)\n\n\n"
  },
  {
   "title": "Node Addresses",
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 17, "y": 0 },
   "content": "| Host         | Name      | IP            |\n|--------------|-----------|---------------|\n| uphsvlndc119 | minion-01 | 170.166.23.4  |\n| uphsvlndc120 | minion-02 | 170.166.23.5  |\n| uphsvlndc142 | minion-03 | 170.166.23.30 |\n| uphsvlndc143 | minion-04 | 170.166.23.31 |\n| uphsvlndc144 | minion-05 | 170.166.23.32 |\n| uphsvlndc145 | minion-06 | 170.166.23.33 |\n| uphsvlndc146 | minion-07 | 170.166.23.34 |\n| uphsvlndc147 | minion-08 | 170.166.23.35 |\n\n\n"
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes)/1e9), \"Host\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{Host}}"
    },
    { "legendFormat": "Memory Available" }
   ]
  },
  {
   "title": "Disk used (\"/\")",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(((node_filesystem_size_bytes{mountpoint=\"/rootfs\"} - node_filesystem_avail_bytes{mountpoint=\"/rootfs\"}) / node_filesystem_size_bytes{mountpoint=\"/rootfs\"} * 100) , \"Host\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{Host}}"
    }
   ]
  }
 ]
}