global:
  slack_api_url: "https://hooks.slack.com/services/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"
route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - match:
      severity: error
  receiver: 'alert-team'
receivers:
- name: 'alert-team'
  slack_configs:
  - channel: "#grafana"
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
