global:
  # url for grafana channel, not currently used for alertmanager
  # slack_api_url: "https://hooks.slack.com/services/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"
  slack_api_url: "https://hooks.slack.com/services/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"
route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - match:
      severity: error
  receiver: 'alert-team'
receivers:
- name: 'alert-team'
  slack_configs:
  - channel: "#alertmanager"
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
