server:
    http_listen_port: 9080
    grpc_listen_port: 0 
  
positions:
    filename: /tmp/positions.yaml

client:
  url: 'http://170.166.23.4:3100/loki/api/v1/push'

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - "localhost"
    labels:
      job: varlogs
      __path__: /alloc/logs/* 

- job_name:  docker
  static_configs:
  - targets:
      - localhost
    labels:
      job: dockerlogs
      app: web_app
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
  - match:
      selector: '{job="dockerlogs"} |~ "- (INFO|WARNING|ERROR) -"'
      stages:
      - regex:
          expression: '\D+(?P<app_time>[^ ]+ [^ ]+)[^a-z]+(?P<service>\S+)\W+(?P<level>\w+)[^{]+(?P<data>.*)\\n'
      - template:
          source: data
          template: '{{ Replace .Value "\\" "" -1 }}'
      - labels:
          service: 
          level: 
      - output:
          source: data
      - metrics:
          service_INFO_messages_total:
              type: Counter
              description: "INFO messages from pennsignalls services containing payload"
              source: service
              config: 
                  match_all: true
                  action: inc      
                  
- job_name: syslog
  syslog:
    listen_address: 0.0.0.0:1514
    idle_timeout: 60s
    label_structured_data: yes
    labels:
      job: "syslog"
  relabel_configs:
    - source_labels: ['__syslog_message_hostname']
      target_label: 'host'

- job_name: 'nomad_metrics'

  consul_sd_configs:
  - server: 'https://uphsvlndc155.uphs.upenn.edu:8500'
    scheme: "https"
    tls_config:
      insecure_skip_verify: true
    services: ['nomad-client', 'nomad']

  relabel_configs:
  - source_labels: ['__meta_consul_tags']
    regex: '(.*)http(.*)'
    action: keep