server:
    http_listen_port: 9080
    grpc_listen_port: 0 
  
positions:
    filename: /tmp/positions.yaml

client:
  url: 'http://170.166.23.4:3100/loki/api/v1/push'

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - "localhost"
    labels:
      job: varlogs
      app: testapp
      __path__: /alloc/logs/*

- job_name: journal
  journal:
    json: false
    max_age: 12h
    path: /var/log/journal
    labels:
      job: systemd-journal
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'

- job_name:  docker
  static_configs:
  - targets:
      - localhost
    labels:
      job: dockerlogs
      app: web_app
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
  - match:
      selector: '{app="web_app"} |~ "- [A-Z]+ -"'
      stages:
      - regex:
          expression: '^(?s)[^0-9]+(?P<time>[^ ]+ [^ ]+)[^a-z]+(?P<service>\S+)[ |-]+(?P<level>\S+)[ |-]+(?P<payload>.*)$'
      - labels:
          service:
          level:
      - output:
          source: payload
      - metrics:
          service_INFO_messages_total:
              type: Counter
              description: "INFO messages from pennsignalls services containing payload"
              source: service
              config: 
                  match_all: true
                  action: inc
                  
- job_name: syslog
  syslog:
    listen_address: 0.0.0.0:1514
    idle_timeout: 60s
    label_structured_data: yes
    labels:
      job: "syslog"
  relabel_configs:
    - source_labels: ['__syslog_message_hostname']
      target_label: 'host'

- job_name: 'nomad_metrics'

  consul_sd_configs:
  - server: 'https://uphsvlndc155.uphs.upenn.edu:8500'
    services: ['nomad-client', 'nomad']

  relabel_configs:
  - source_labels: ['__meta_consul_tags']
    regex: '(.*)http(.*)'
    action: keep